# Generated by Django 5.2.7 on 2025-10-19 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('money_inserted', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('change', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendingmachine.items')),
            ],
        ),
    ]
